#!/bin/bash
hostname=`hostname`
export CMS_XROOTD_CACHE="$hostname":4095
export ATLAS_XROOTD_CACHE="$hostname":4094
exec "$@"
error=$?
echo "Failed to exec($error): $@" > $_CONDOR_WRAPPER_ERROR_FILE
exit 1
